version: '3.8'
services:
  database:
    image: postgres:13
    container_name: band_portfolio_db
    restart: always
    environment:
      POSTGRES_USER: band_portfolio
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: band_portfolio_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend

  backend:
    build: .
    container_name: band_portfolio_backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      # Используем DATABASE_URL вместо отдельных переменных
      - DATABASE_URL=postgresql://band_portfolio:password123@database:5432/band_portfolio_db
      - JWT_SECRET=your-super-secret-jwt-key-for-band-portfolio
    depends_on:
      - database
    # Убираем volume для production или делаем только для uploads
    volumes:
      - uploads_data:/app/uploads
    networks:
      - backend
      - frontend

  swagger:
    build:
      context: .
      dockerfile: Dockerfile.swagger
    container_name: band_portfolio_swagger
    restart: always
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - SWAGGER_PORT=3001
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - frontend
    depends_on:
      - backend
  nginx:
    image: nginx:alpine
    container_name: band_portfolio_nginx
    restart: always
    ports:
      - "8080:808"
    volumes:
     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
    networks:
      - frontend
      - backend

  adminer:
    image: adminer:4
    container_name: band_portfolio_adminer
    restart: always
    ports:
      - '8081:8080'
    environment:
      ADMINER_DEFAULT_SERVER: database
      ADMINER_DESIGN: pepa-linha
    networks:
      - backend

volumes:
  postgres_data:
  uploads_data:

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge